trigger:
  - master

pool:
  name: Azure Pipelines
  vmImage: "windows-2019"

steps:
  - task: UseDotNet@2
    displayName: "use .Net Core SDK 3.1.x"
    inputs:
      version: 3.1.x

  - task: DotNetCoreCLI@2
    displayName: build
    inputs:
      projects: "**/Tests.Performance.csproj"
      arguments: "--configuration Release"

  - task: DotNetCoreCLI@2
    displayName: "run benchmarks"
    inputs:
      command: run
      projects: "**/Tests.Performance.csproj"
      arguments: "--configuration Release --no-restore --no-build"

  - task: CopyFiles@2
    displayName: "stage artifacts"
    inputs:
      SourceFolder: tests/performance
      Contents: "**/BenchmarkDotNet.Artifacts/results"
      TargetFolder: "$(Build.ArtifactStagingDirectory)"
      CleanTargetFolder: true
      OverWrite: true
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: "save artifacts"
    inputs:
      ArtifactName: packages
