trigger:
  - master

pr:
  - master

stages:

  - stage: DotNet
    jobs:
    - job: DotNetTest
      pool:
        name: Azure Pipelines
        vmImage: "ubuntu-latest"

      variables:
        BuildConfiguration: "Release"

      steps:
        - task: UseDotNet@2
          displayName: "use .NET SDK 5.0.x"
          inputs:
            version: 5.0.x

        - task: NuGetToolInstaller@1
          displayName: "use NuGet 5.8.x"
          inputs:
            versionSpec: 5.8.x
            checkLatest: false

        - task: DotNetCoreCLI@2
          displayName: "use GitVersion"
          inputs:
            command: custom
            custom: tool
            arguments: "install -g gitversion.tool --version 5.6.8"

        - task: DotNetCoreCLI@2
          displayName: "get version number"
          inputs:
            command: custom
            custom: gitversion
            arguments: "/output buildserver"

        - task: DotNetCoreCLI@2
          displayName: "create assembly info"
          inputs:
            command: "custom"
            custom: "gitversion"
            arguments: "/updateassemblyinfo AssemblyInfo.cs /ensureassemblyinfo"

        - task: DotNetCoreCLI@2
          displayName: build
          inputs:
            projects: "**/*.csproj"
            arguments: "--configuration $(BuildConfiguration) /p:Version=$(GitVersion.NuGetVersion)"

        - task: DotNetCoreCLI@2
          displayName: "test internal"
          inputs:
            command: test
            projects: "**/Tests.Indicators.csproj"
            arguments: "--configuration $(BuildConfiguration) --no-restore --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura"
            testRunTitle: ".NET Tests(Internal)"

        - task: DotNetCoreCLI@2
          displayName: "test external"
          inputs:
            command: test
            projects: "**/Tests.External.csproj"
            arguments: "--configuration $(BuildConfiguration) --no-restore --no-build /p:CollectCoverage=false"
            publishTestResults: false
            testRunTitle: ".NET Tests(External)"

        - task: PublishCodeCoverageResults@1
          displayName: "publish code coverage"
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: "$(Build.SourcesDirectory)/tests/indicators/coverage.cobertura.xml"

        - task: DotNetCoreCLI@2
          displayName: "pack for NuGet"
          inputs:
            command: "pack"
            packagesToPack: "indicators/Indicators.csproj"
            nobuild: true
            versioningScheme: "byEnvVar"
            versionEnvVar: "GitVersion.NuGetVersion"

        - task: CopyFiles@2
          displayName: "stage artifacts"
          inputs:
            SourceFolder: "indicators"
            Contents: "**/*.nupkg"
            TargetFolder: "$(Build.ArtifactStagingDirectory)"
            CleanTargetFolder: true
            OverWrite: true
            flattenFolders: true
        
        - task: CopyFiles@2
          displayName: "stage DLLs"
          inputs:
            SourceFolder: "indicators/bin/Release"
            Contents: "**"
            TargetFolder: "$(Build.ArtifactStagingDirectory)/DLLs"
            OverWrite: true

        - task: PublishBuildArtifacts@1
          displayName: "save artifacts"
          inputs:
            ArtifactName: packages

  - stage: Python
    jobs:
    - job: PythonTest
      variables:
        PythonWrapperBaseDirectory: "$(Build.SourcesDirectory)/wraps/python"
        DotNetVersion: "netstandard2.0"

      strategy:
        matrix:
          Windows-Python38:
            imageName: windows-2019
            python.version: '3.8'
          Windows-Python39:
            imageName: windows-2019
            python.version: '3.9'
          Linux-Python38:
            imageName: ubuntu-latest
            python.version: '3.8'
          Linux-Python39:
            imageName: ubuntu-latest
            python.version: '3.9'

      pool:
        name: Azure Pipelines
        vmImage: '$(imageName)'

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          
      - script: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pythonnet
        displayName: 'Install dependencies'

      - task: DownloadPipelineArtifact@2
        displayName: "Fetch DLL from artifacts"
        inputs:
          artifact: packages
          patterns: 'packages/DLLs/$(DotNetVersion)/*.dll'

      - task: CopyFiles@2
        displayName: "Replace DLL"
        inputs:
          SourceFolder: "$(Pipeline.Workspace)/DLLs/$(DotNetVersion)"
          Contents: "*.dll"
          TargetFolder: "$(PythonWrapperBaseDirectory)/lib"
          CleanTargetFolder: true
          OverWrite: true
          flattenFolders: true

      - script: |
          pip install pytest pytest-cov openpyxl
          pytest -vr A --junitxml=$(PythonWrapperBaseDirectory)/tests/test-results.xml --cov=$(PythonWrapperBaseDirectory)/SkenderStockIndicators --cov-report xml:$(PythonWrapperBaseDirectory)/tests/coverage.xml
        displayName: 'Run all tests'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: '$(PythonWrapperBaseDirectory)/tests/test-results.xml'
          testRunTitle: 'Python $(python.version) Tests'

# Duplicated publishing process
#      - task: PublishCodeCoverageResults@1
#        inputs:
#          codeCoverageTool: Cobertura
#          summaryFileLocation: '$(PythonWrapperBaseDirectory)/tests/coverage.xml'

          