# Dependabot configuration
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "monthly"
