# GitHub Issue and Pull Request Labels
# This file documents the labeling system for Stock Indicators for .NET

## Issue Labels

### Type Labels (Primary Classification)
- **bug** 🐛
  - Color: #d73a4a
  - Description: Something isn't working correctly
  - Used for: Confirmed defects, incorrect calculations, exceptions

- **enhancement** ✨
  - Color: #a2eeef
  - Description: New feature or improvement request
  - Used for: New indicators, API improvements, performance enhancements

- **documentation** 📚
  - Color: #0075ca
  - Description: Improvements or additions to documentation
  - Used for: README updates, API docs, examples, guides

- **question** ❓
  - Color: #d876e3
  - Description: Further information is requested
  - Used for: Usage questions, clarifications, discussions

### Priority Labels
- **priority-critical** 🚨
  - Color: #b60205
  - Description: Critical issue requiring immediate attention
  - Used for: Security vulnerabilities, data corruption, breaking bugs

- **priority-high** 🔴
  - Color: #e99695
  - Description: High priority issue
  - Used for: Major feature requests, significant bugs

- **priority-low** 🟡
  - Color: #fbca04
  - Description: Low priority issue
  - Used for: Minor improvements, nice-to-have features

### Difficulty Labels
- **good first issue** 👋
  - Color: #7057ff
  - Description: Good for newcomers
  - Used for: Simple fixes, documentation updates, beginner-friendly tasks

- **help wanted** 🙋
  - Color: #008672
  - Description: Extra attention is needed
  - Used for: Complex issues that need community help

- **advanced** 🎓
  - Color: #5319e7
  - Description: Requires advanced knowledge
  - Used for: Complex mathematical implementations, performance optimizations

### Component Labels
- **indicator** 📊
  - Color: #0e8a16
  - Description: Related to technical indicators
  - Used for: New indicators, indicator bugs, calculation issues

- **api** 🔧
  - Color: #1d76db
  - Description: Related to public API
  - Used for: Breaking changes, API design, method signatures

- **performance** ⚡
  - Color: #f9d0c4
  - Description: Performance-related
  - Used for: Speed improvements, memory optimizations, benchmarks

- **testing** 🧪
  - Color: #c5def5
  - Description: Related to testing
  - Used for: Test improvements, coverage, test failures

- **ci-cd** 🔄
  - Color: #fef2c0
  - Description: Continuous integration and deployment
  - Used for: GitHub Actions, build scripts, deployment issues

### Status Labels
- **duplicate** 🔄
  - Color: #cfd3d7
  - Description: This issue or pull request already exists
  - Used for: Closing duplicate issues

- **wontfix** ❌
  - Color: #ffffff
  - Description: This will not be worked on
  - Used for: Issues that won't be addressed by design

- **blocked** 🚫
  - Color: #b60205
  - Description: Blocked by another issue or external factor
  - Used for: Issues waiting on dependencies or decisions

- **in-progress** 🚧
  - Color: #fbca04
  - Description: Currently being worked on
  - Used for: Active development, assigned issues

### Special Labels
- **breaking-change** ⚠️
  - Color: #ff6b6b
  - Description: Contains breaking changes
  - Used for: API changes, behavioral changes affecting existing users

- **new-indicator** 🆕
  - Color: #28a745
  - Description: Adds a new technical indicator
  - Used for: Pull requests adding new indicators

- **dependencies** 📦
  - Color: #0366d6
  - Description: Pull requests that update dependencies
  - Used for: Dependabot PRs, manual dependency updates

- **automated** 🤖
  - Color: #70f0a6
  - Description: Automated pull requests
  - Used for: Dependabot, auto-generated PRs

## Pull Request Labels

Pull requests use the same label system as issues, with additional labels:

- **needs-review** 👀
  - Color: #ff9500
  - Description: Ready for code review
  - Used for: PRs awaiting reviewer attention

- **changes-requested** 📝
  - Color: #fc2929
  - Description: Changes have been requested by reviewers
  - Used for: PRs requiring modifications before merge

- **approved** ✅
  - Color: #0e8a16
  - Description: Approved by reviewers
  - Used for: PRs ready to merge

## Automated Labeling

Some labels are automatically applied by GitHub Actions:
- **dependencies** - Applied to Dependabot PRs
- **automated** - Applied to bot-generated PRs
- **documentation** - Applied when only docs files are changed

## Label Management

Labels should be:
- Applied consistently across issues and PRs
- Updated as issues evolve
- Used to facilitate filtering and project board automation
- Helpful for GitHub Copilot and contributors to understand scope and priority

## Project Board Integration

Labels are used to automatically organize issues in our [project board](https://github.com/users/DaveSkender/projects/1):

- **To Do**: New issues without `in-progress` label
- **In Progress**: Issues with `in-progress` label
- **Review**: PRs with `needs-review` label
- **Done**: Closed issues and merged PRs