# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
# documentation: https://docs.coderabbit.ai/reference/configuration
# CodeRabbit Configuration for Stock Indicators for .NET
# Optimized for financial calculation accuracy, performance, and .NET best practices

# General settings
language: "en-US"
early_access: false

# Review configuration
reviews:
  profile: "chill" # Balanced approach - thorough but not overwhelming
  request_changes_workflow: false
  high_level_summary: false
  poem: false
  review_status: true
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  in_progress_fortune: false
  collapse_walkthrough: false

  # Automatic review scheduling
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - v*

  # Files to include/exclude from reviews
  path_filters:
    - "**/*"
    - "!**/*.Designer.cs"    # Generated designer files
    - "!**/bin/**"           # Build output
    - "!**/obj/**"           # Build intermediate files
    - "!**/*.g.cs"           # Generated source files
    - "!**/node_modules/**"  # NPM dependencies
    - "!**/.vs/**"           # Visual Studio files
    - "!**/packages/**"      # NuGet packages cache
    - "!**/*.bak"            # Backup files
    - "!**/.jekyll-cache/**" # Jekyll cache
    - "!**/Gemfile.lock"     # Ruby dependencies lock
    - "!**/*.Calc.xlsx"      # Manual calculation spreadsheets (test artifacts)

  # Path-based configuration
  path_instructions:
    # Indicator documentation pages must stay aligned with the current API surface
    - path: "docs/_indicators/*.md"
      instructions: |
        Keep each indicator page synchronized with its public API:
        - Refresh the primary usage example (extension method and `Get{Indicator}` call) to match the latest signature and defaults
        - Document required and optional parameters, warmup expectations, and key output columns
        - Note any behavior changes, streaming considerations, or spec references introduced by the PR

    # Source code - Focus on financial accuracy and performance
    - path: "src/**/*.cs"
      instructions: |
        Focus on:
        - **Mathematical accuracy**: Verify financial calculations against reference implementations
        - **Performance**: Flag unnecessary allocations, excessive LINQ, boxing operations
        - **Precision**: Ensure appropriate use of `double` vs `decimal` for financial calculations
        - **Null safety**: Validate handling of insufficient data scenarios
        - **Input validation**: Check parameter validation and error handling
        - **Lookback periods**: Verify off-by-one errors in window calculations
        - **Streaming support**: Ensure stateful indicators handle edge cases properly
        - **Memory efficiency**: Check for proper span usage and buffer management
        - **XML documentation**: Ensure all public APIs have complete documentation

    # Test files - Ensure comprehensive coverage and accuracy validation
    - path: "tests/**/*.cs"
      instructions: |
        Review for:
        - **Test coverage**: Ensure edge cases and boundary conditions are tested
        - **Mathematical validation**: Verify tests use manually calculated results
        - **Performance tests**: Check benchmark tests for regression detection
        - **Integration tests**: Validate API compatibility and chaining scenarios
        - **Streaming tests**: Ensure real-time scenarios are properly tested
        - **Error scenarios**: Verify exception handling and invalid input tests

    # Catalog files - API definition accuracy
    - path: "**/*.Catalog.cs"
      instructions: |
        Verify:
        - **Parameter definitions**: Check types, defaults, constraints match implementation
        - **Result definitions**: Ensure property names match Models exactly
        - **IReusable flags**: Verify only one result per indicator has isReusable=true
        - **Method names**: Follow To{IndicatorName} pattern consistently
        - **Category assignments**: Use appropriate technical analysis categories

    # Documentation - Accuracy and completeness
    - path: "docs/**/*.md"
      instructions: |
        Check for:
        - **Accuracy**: Ensure content matches current implementation
        - **Completeness**: Verify examples, parameters, and return values are documented
        - **Accessibility**: Flag missing alt text, poor heading hierarchy
        - **Link validity**: Check for broken internal/external links
        - **Mathematical formulas**: Verify calculation descriptions are correct

    # Jekyll site files
    - path: "docs/**/*.{html,liquid,scss,js}"
      instructions: |
        Focus on:
        - **Accessibility**: WCAG compliance, semantic HTML, proper ARIA labels
        - **Performance**: Optimize images, minimize CSS/JS, efficient loading
        - **Mobile responsiveness**: Ensure layouts work across devices
        - **SEO**: Check meta tags, structured data, semantic markup

    # Configuration and workflow files
    - path: ".github/**/*.yml"
      instructions: |
        Review for:
        - **Security**: No secrets in workflows, proper permissions
        - **Efficiency**: Optimize CI/CD performance, avoid redundant builds
        - **Dependencies**: Keep actions and versions current
        - **Error handling**: Proper failure scenarios and notifications

    # Project files and build configuration
    - path: "**/*.{csproj,props,targets,sln}"
      instructions: |
        Verify:
        - **Version consistency**: Package versions, target frameworks alignment
        - **Security**: No vulnerable packages, proper security settings
        - **Performance**: Compiler optimizations enabled for release builds
        - **Analyzers**: Code quality rules properly configured
        - **Packaging**: NuGet metadata complete and accurate

  # Tool integrations
  tools:
    gitleaks:
      enabled: true
    semgrep:
      enabled: true
    osvScanner:
      enabled: true
    markdownlint:
      enabled: true
    yamllint:
      enabled: true
    actionlint:
      enabled: true
    shellcheck:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 120000
    eslint:
      enabled: false
    ruff:
      enabled: false
    golangci-lint:
      enabled: false
    hadolint:
      enabled: false
    checkov:
      enabled: false
    htmlhint:
      enabled: false
    languagetool:
      enabled: false
    biome:
      enabled: false
    oxc:
      enabled: false

  # Disable automatic finishing touches to keep reviews focused on manual intent
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false

  # Pre-merge checks keep contributors aligned with workflow guardrails
  pre_merge_checks:
    title:
      mode: "warning"
      requirements: |
        PR titles must follow the Conventional Commit format `type: Subject`, where `type` is one of {feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert, plan} and `Subject` starts uppercase and stays ≤ 65 characters.

# Knowledge base configuration
# Domain highlights:
# - This is a .NET library for technical analysis indicators used in financial markets
# - Performance is critical; prefer `double` over `decimal` unless business accuracy requires it
# - Indicators must handle insufficient data with null-safe patterns and enforce lookback rules
# - Streaming indicators maintain state between updates for real-time scenarios
# - Documentation and instructions live in .github/instructions and related guideline files
knowledge_base:
  opt_out: false
  code_guidelines:
    enabled: true
    filePatterns:
      - ".github/copilot-instructions.md"
      - ".github/instructions/*.instructions.md"
      - ".github/instructions/**/*.instructions.md"
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  pull_requests:
    scope: "auto"
  mcp:
    usage: "auto"

# Custom checks for financial calculations
checks:
  # Financial accuracy patterns
  - pattern: "decimal.*price"
    message: "Consider if `decimal` precision is necessary for this price calculation. Default to `double` for performance unless business accuracy requires decimal precision."

  - pattern: "double\\.NaN"
    message: "Ensure NaN handling is appropriate for this financial calculation scenario."

  # Performance patterns
  - pattern: "\\.ToList\\(\\)"
    message: "Avoid unnecessary .ToList() calls in performance-critical paths. Consider using spans or direct enumeration."

  - pattern: "LINQ.*\\.Where.*\\.Select.*\\.Where"
    message: "Multiple LINQ chains may impact performance. Consider consolidating or using span-based operations."

  # Validation patterns
  - pattern: "ArgumentOutOfRangeException"
    message: "Ensure lookback period validation includes edge cases and provides clear error messages."

  # Documentation patterns
  - pattern: "public.*class.*\\{[^/]*$"
    message: "Public classes should have XML documentation comments explaining their purpose and usage."

  - pattern: "public.*\\(.*\\).*=>.*;"
    message: "Public methods should include XML documentation with parameter descriptions and return value details."

# Integration with existing tools
integration:
  # Respect existing .editorconfig rules
  editorconfig: true

  # Work with existing analyzers
  dotnet_analyzers: true

  # Coordinate with existing GitHub workflows
  github_actions: true

# Metrics and reporting preferences
reporting:
  # Key metrics for this repository type
  metrics:
    - "test_coverage"
    - "code_duplication"
    - "cyclomatic_complexity"
    - "maintainability_index"
    - "performance_indicators"

  # Focus areas for dashboard
  focus_areas:
    - "mathematical_accuracy"
    - "performance_optimization"
    - "api_consistency"
    - "documentation_completeness"
    - "test_coverage"

# Custom review templates
templates:
  performance_review: |
    ## Performance Analysis
    - [ ] No unnecessary allocations in hot paths
    - [ ] Appropriate use of spans for array operations
    - [ ] LINQ usage optimized for performance
    - [ ] Proper handling of large datasets

  financial_accuracy: |
    ## Financial Calculation Review
    - [ ] Mathematical formulas verified against references
    - [ ] Precision appropriate (double vs decimal)
    - [ ] Edge cases handled (insufficient data, overflow)
    - [ ] Lookback periods calculated correctly

  api_consistency: |
    ## API Design Review
    - [ ] Method names follow To{IndicatorName} pattern
    - [ ] Parameter validation comprehensive
    - [ ] Return types consistent with similar indicators
    - [ ] XML documentation complete and accurate
