path_classifiers:
  docs:
    - exclude: docs
  test:
    - tests
    - exclude: tests/performance
extraction:
  csharp:
    index:
      all_solutions: false
      solution:
        - Stock.Indicators.sln
      dotnet:
        version: "7.0.x"
      build_command:
        - dotnet restore
        - dotnet build
