namespace Regression;

/// <summary>
/// Regression tests for Price Relative Strength (PRS) indicator.
/// Note: All regression tests are skipped because PRS uses SeriesParameter (dual-input)
/// which cannot be auto-generated by the baseline tool.
/// Static series tests in Prs.StaticSeries.Tests.cs provide comprehensive coverage.
/// See docs/plans/pairhubs.plan.md for details.
/// </summary>
[TestClass, TestCategory("Regression")]
public class PrsTests : RegressionTestBase<PrsResult>
{
    public PrsTests() : base("prs.standard.json") { }

    [TestMethod]
    public override void Series() => Assert.Inconclusive("Dual-input indicator - see StaticSeries tests");

    [TestMethod]
    public override void Buffer() => Assert.Inconclusive("BufferList removed - see pairhubs.plan.md");

    [TestMethod]
    public override void Stream() => Assert.Inconclusive("StreamHub removed - see pairhubs.plan.md");
}
