name: Bug report
description: File a bug report.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time report a bug in the [Skender.Stock.Indicators NuGet library](https://www.nuget.org/packages/Skender.Stock.Indicators)!
        > [!NOTE]
        > Please review [Help! Results don't match TradingView!](https://github.com/DaveSkender/Stock.Indicators/discussions/801), [known issues](https://github.com/DaveSkender/Stock.Indicators/issues?q=is%3Aissue), and [discussions](https://github.com/DaveSkender/Stock.Indicators/discussions) before submitting a new bug report.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: and what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: usage
    attributes:
      label: Code usage snippet
      description: |
        How did you write your code?  Provide a code snippet.
        This will be automatically formatted into code, so no need for `backticks`.
        Also, consider uploading the historical `quotes` you used (as a JSON, CSV, or Excel file).
      render: shell
      placeholder: |
        var results = quotes.GetEma(14);
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: |
        Please copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for `backticks`.
      render: shell
  - type: input
    id: version
    attributes:
      label: Version
      description: What package version are you using?
  - type: markdown
    attributes:
      value: |
        If your request is urgent, please review our [sponsorship tiers](https://github.com/sponsors/facioquo).
        If you require contract custom development, please [contact Skender Co.](https://skenderco.com), our parent organization.
