name: Feature request
description: Suggest an idea for this project.
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you &#128150; for taking the time to make a recommendation for the [`Skender.Stock.Indicators` NuGet library](https://www.nuget.org/packages/Skender.Stock.Indicators)! If you have an idea that you don't want us to track in [our backlog](https://github.com/users/DaveSkender/projects/1), consider posting in our community [discussions](https://github.com/DaveSkender/Stock.Indicators/discussions).
  - type: textarea
    id: request
    attributes:
      label: the problem
      description: What problem are you trying to solve? Or, what outcome do you want achieve? Why?
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: markdown
    attributes:
      value: If your request is urgent, please review our [sponsorship tiers](https://github.com/sponsors/facioquo). For contract custom development, contact [Skender Co.](https://skenderco.com)
