name: Copilot Setup Steps

on:
  workflow_dispatch:
    inputs:
      restore_tools:
        description: 'Restore development tools'
        required: false
        default: true
        type: boolean
      update_dependencies:
        description: 'Update package dependencies'
        required: false
        default: false
        type: boolean

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          
    - name: Setup Node.js
      if: inputs.restore_tools
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Enable Corepack
      if: inputs.restore_tools
      run: corepack enable
      
    - name: Install Python and uv
      if: inputs.restore_tools
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      if: inputs.restore_tools
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
    - name: Install Spec Kit
      if: inputs.restore_tools
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        uv tool install specify-cli --from git+https://github.com/github/spec-kit.git
        
    - name: Restore .NET packages
      run: dotnet restore
      
    - name: Install Node.js dependencies
      if: inputs.restore_tools
      run: npm install
      
    - name: Update dependencies
      if: inputs.update_dependencies
      run: |
        dotnet list package --outdated
        npm audit
        
    - name: Verify setup
      run: |
        dotnet --info
        node --version
        npm --version
        echo "Setup completed successfully"