namespace Regression;

/// <summary>
/// Regression tests for Beta indicator.
/// Note: All regression tests are skipped because Beta uses SeriesParameter (dual-input)
/// which cannot be auto-generated by the baseline tool.
/// Static series tests in Beta.StaticSeries.Tests.cs provide comprehensive coverage.
/// See docs/plans/pairhubs.plan.md for details.
/// </summary>
[TestClass, TestCategory("Regression")]
public class BetaTests : RegressionTestBase<BetaResult>
{
    public BetaTests() : base("beta.standard.json") { }

    [TestMethod]
    public override void Series() => Assert.Inconclusive("Dual-input indicator - see StaticSeries tests");

    [TestMethod]
    public override void Buffer() => Assert.Inconclusive("BufferList removed - see pairhubs.plan.md");

    [TestMethod]
    public override void Stream() => Assert.Inconclusive("StreamHub removed - see pairhubs.plan.md");
}
