namespace Skender.Stock.Indicators;

/// <summary>
/// Auto-generated catalog of all indicators in the library.
/// This is a placeholder class that will be replaced by the source generator.
/// </summary>
public static partial class GeneratedCatalog
{
    /// <summary>
    /// Gets the complete list of indicators
    /// </summary>
    public static IReadOnlyList<IndicatorListing> Indicators => GeneratedIndicators;

    /// <summary>
    /// Gets the complete list of indicators
    /// </summary>
    /// <remarks>This will be auto-generated by the source generator</remarks>
    private static partial IReadOnlyList<IndicatorListing> GeneratedIndicators { get; }
}
