source 'https://rubygems.org'

# jekyll plugins
group :jekyll_plugins do
  gem 'github-pages'
  gem "jekyll-github-metadata"
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jekyll-last-modified-at' # used in sitemap
  gem 'jekyll-redirect-from'
  gem 'jekyll-minifier'
end

platforms :mingw, :mswin, :x64_mingw do
  gem 'wdm', '>= 0.2.0' # windows compatibility pack
end

gem 'webrick'           # needed for ruby > v3.0
gem 'faraday'           # reload/retry on file changes
