source 'https://rubygems.org'
# local dev: bundle exec jekyll serve -o -l

# jekyll plugins
group :jekyll_plugins do
  gem 'github-pages'
  gem "jekyll-github-metadata"
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jekyll-last-modified-at' # used in sitemap
  gem 'jekyll-redirect-from'
  gem 'jekyll-minifier'
end

gem 'wdm', '>= 0.2.0' if Gem.win_platform? # windows compatibilty pack
gem 'webrick' # needed for ruby > v3.0
gem 'faraday' # reload/retry on file changes
