name: docs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./docs

jobs:
  build:
    name: test URLs
    runs-on: ubuntu-latest
    env:
      LANG: en_US.UTF-8
      LANGUAGE: en_US
      LC_ALL: en_US.UTF-8

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Ruby environment
        run: |
          sudo apt-get update;
          sudo apt-get install --reinstall -y locales;
          sudo sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen;
          sudo locale-gen en_US.UTF-8;

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Serve site
        run: bundle exec jekyll serve --detach

      - name: Test for broken URLs
        run: bundle exec htmlproofer _site
