name: Indicators

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:

  test:
    name: unit tests
    runs-on: ubuntu-latest

    steps:

      - name: Clean workspace
        run: |
          rm -rf ./test-indicators/* || true
          rm -rf ./test-indicators/.??* || true
          rm -rf ./NuGet/* || true
          rm -rf ./NuGet/.??* || true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"
          dotnet-quality: "ga"

      - name: Build solution
        run: >
          dotnet build
          --configuration Release
          --property:ContinuousIntegrationBuild=true
          -warnAsError

      - name: Test indicators
        id: test-library
        env:
          ALPACA_KEY: ${{ secrets.ALPACA_KEY }}
          ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}
        run: >
          dotnet test tests/indicators/Tests.Indicators.csproj
          --configuration Release
          --no-build
          --verbosity normal
          --logger trx
          --collect:"XPlat Code Coverage"
          --results-directory ./test-indicators

      - name: Test other items
        id: test-other
        run: >
          dotnet test tests/other/Tests.Other.csproj
          --configuration Release
          --no-build
          --verbosity normal
          --logger trx
          --results-directory ./test-other

      - name: Update tests summary
        uses: bibipkins/dotnet-test-reporter@v1.3.3
        if: ${{ github.event_name == 'pull_request' && (success() || (failure() && (steps.test-library.conclusion == 'failure' || steps.test-other.conclusion == 'failure'))) }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: ""
          results-path: ./test-indicators/**/*.trx
          coverage-path: ./test-indicators/**/coverage.cobertura.xml
          coverage-type: cobertura
          coverage-threshold: 95
