name: "Performance"

on:
  push:
    branches: ["main"]
    paths:
      - 'src/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'

jobs:
  analyze:
    name: benchmark
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Build solution
        run: dotnet build -c Release