name: "build and test"

on:
  push:
    branches: ["main"]
    paths:
      - 'src/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'

jobs:
  analyze:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Setup GitVersion
        run: dotnet tool install --global GitVersion.Tool --version 5.*

      - name: Get semantic version
        run: dotnet-gitversion >
          /config gitversion.yml
          /updateassemblyinfo
          /output

      - name: Build solution
        run: dotnet build >
          --configuration Release
          /p:Version=${{env.GitVersion.NuGetVersion}}
          /p:ContinuousIntegrationBuild=true
          /warnaserror

      - name: Test library
        run: dotnet test >
            tests/indicators/Tests.Indicators.csproj
          --configuration Release
          --no-restore
          --no-build
          --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura