name: Deploy website

on: [workflow_dispatch]

concurrency:
  group: cloudflare-pages

env:
  JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    name: Cloudflare Pages
    runs-on: ubuntu-latest

    environment:
      name: cloudflare-pages

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: docs
          ruby-version: 3.1.3
          bundler-cache: false

      - name: Install GEMs
        working-directory: docs
        env:
          BUNDLE_GEMFILE: ${{github.workspace}}/docs/GemFile
        run: |
          pwd
          bundle install

      - name: Build site (production)
        if: github.ref == 'refs/heads/main'
        working-directory: docs
        env:
          JEKYLL_ENV: production
          BUNDLE_GEMFILE: ${{github.workspace}}/docs/GemFile
        run: bundle exec jekyll build

      - name: Build site (preview)
        if: github.ref != 'refs/heads/main'
        working-directory: docs
        env:
          JEKYLL_ENV: preview
          BUNDLE_GEMFILE: ${{github.workspace}}/docs/GemFile
        run: bundle exec jekyll build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: docs/_site
          wranglerVersion: 'latest'