name: test docs
on:
  pull_request:
    branches: [main]

env:
  BUNDLE_GEMFILE: ${{github.workspace}}/docs/GemFile

jobs:
  testing:
    name: URLs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: docs
          ruby-version: 3.1
          bundler-cache: false

      - name: Install GEMs
        working-directory: docs
        run: |
          pwd
          bundle install

      - name: Build site
        working-directory: docs
        run: bundle exec jekyll build

      - name: Serve site
        working-directory: docs
        run: bundle exec jekyll serve --detach

      - name: Test for broken URLs
        working-directory: docs
        run: |
          bundle exec htmlproofer _site \
            --assume-extension \
            --ignore-status-codes "403,406,429,503,999" \
            --swap-urls "https\://dotnet.stockindicators.dev:http\://127.0.0.1:4000" \
            --ignore-urls "/fonts.gstatic.com/"
