name: test docs
on:
  pull_request:
    branches: [main]

jobs:
  testing:
    name: URLs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: docs
          ruby-version: 2.7.0
          bundler-cache: true

      - name: Install GEMs
        working-directory: docs
        run: |
          pwd
          BUNDLE_GEMFILE="${{github.workspace}}/docs/GemFile" bundle install

      - name: Cache HTMLProofer
        id: cache-htmlproofer
        uses: actions/cache@v2
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer

      - name: Build site
        working-directory: docs
        run: BUNDLE_GEMFILE="${{github.workspace}}/docs/GemFile" bundle exec jekyll build

      - name: Serve site
        working-directory: docs
        run: BUNDLE_GEMFILE="${{github.workspace}}/docs/GemFile" bundle exec jekyll serve --detach

      - name: Test for broken URLs
        working-directory: docs
        run: |
          BUNDLE_GEMFILE="${{github.workspace}}/docs/GemFile" bundle exec htmlproofer _site \
            --assume-extension \
            --swap-urls "https\://dotnet.stockindicators.dev:http\://127.0.0.1:4000" \
            --ignore-urls fonts.gstatic.com \
            --ignore-status-codes "403,406,429,503,999" \
            --enforce_https false

