name: Code Quality

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

permissions:
  contents: read   # Required for checkout

jobs:
  code-quality:
    name: format and lint checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.x"
          dotnet-quality: "ga"

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "npm"

      - name: Install npm dependencies
        run: npm install

      - name: Check .NET code formatting
        run: dotnet format --verify-no-changes

      - name: Check Markdown linting
        run: npm run lint:md