name: Website UI

on:
  pull_request:
    branches: ["*"]
    paths:
      - docs/**
      - .github/workflows/test-website-ui.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Unit tests (Jest)
        run: npm test -- --ci --runInBand

      - name: Build site
        run: npm run build:complete

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: E2E tests (Playwright)
        run: npm run e2e
